PDA-42 process definition list endpoint
entando/pda-redhatpam-engine pull request #10
Opened 2019-11-27 14:31 UTC by ffleandro

…rver

2019-11-27 14:32 UTC, entando-service commented
Something went wrong. Investigate!

2019-11-27 14:51 UTC, entando-service commented
Something went wrong. Investigate!

2019-11-28 13:29 UTC, werbth requested changes

2019-11-28 13:29 UTC, werbth commented on src/main/java/org/entando/plugins/pda/pam/service/process/KieProcessService.java
> +        pageRequest.setPageSize(2_000_000_000); //Set max page size to get all results
Could you create a constant for this number to improve readability? MAX_PAGE_SIZE maybe?

2019-11-28 13:29 UTC, werbth commented on src/test/java/org/entando/plugins/pda/pam/service/process/KieProcessServiceTest.java
> +    public void shouldListProcessDefinitionsWithFilterAndSort() throws Exception {
This test is exactly the same as `shouldListProcessDefinitions`.

2019-11-28 13:29 UTC, werbth commented on src/test/java/org/entando/plugins/pda/pam/util/KieProcessTestHelper.java
> +    public static ServiceResponse<KieContainerResourceList> createKieContainersResponse() {
This method is not being used.

2019-11-28 13:29 UTC, werbth commented on pom.xml
> +            <groupId>org.powermock</groupId>
Powermock is not being used. Could you remove the dependency, please?

2019-11-28 13:29 UTC, werbth commented on pom.xml
> +            <groupId>org.kie.server</groupId>
Once you remove unused methods, this dependency can be removed.

2019-11-29 13:16 UTC, entando-service commented
Something went wrong. Investigate!

2019-11-29 13:52 UTC, werbth commented
retest this please

2019-11-29 13:53 UTC, entando-service commented
Something went wrong. Investigate!

2019-11-29 13:59 UTC, entando-service commented
All is well

2019-11-29 14:00 UTC, werbth approved these changes

2019-11-29 14:00 UTC, merged