PDA-47 Process Diagram Endpoint
entando/pda-redhatpam-engine pull request #13
Opened 2019-12-04 19:47 UTC by ffleandro

2019-12-04 19:47 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-04 20:21 UTC, werbth commented
retest this please

2019-12-04 20:22 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-05 15:06 UTC, ffleandro commented
Retest this please

2019-12-05 15:07 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-05 20:55 UTC, ffleandro commented
Retest this please

2019-12-05 20:55 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-05 21:37 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-05 21:38 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-06 13:58 UTC, werbth requested changes

2019-12-06 13:58 UTC, werbth commented on src/main/java/org/entando/plugins/pda/pam/service/process/model/KieProcessId.java
> +        if (split.length != 2) { //NOPMD
Create a constant for this literal and you can remove that `NOPMD` comment.

2019-12-06 13:58 UTC, werbth commented on src/main/java/org/entando/plugins/pda/pam/service/group/KieGroupService.java
> +        KieProcessId compositeId = new KieProcessId(id);
The processId here is the process definition. It is a string, so it cannot be used with this KieProcessId object.

2019-12-06 13:58 UTC, werbth commented on src/test/java/org/entando/plugins/pda/pam/service/group/KieGroupServiceTest.java
> +        String processId = "1";
This should be a string with alphanumeric values.

2019-12-06 14:43 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-06 14:48 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-06 23:02 UTC, werbth commented
Retest this please

2019-12-06 23:03 UTC, entando-service commented
All is well

2019-12-06 23:03 UTC, werbth approved these changes

2019-12-06 23:04 UTC, merged