PDA-54 Adding Kie implementation for task form service
entando/pda-redhatpam-engine pull request #17
Opened 2019-12-19 18:32 UTC by BrenoQVDS

2019-12-19 18:32 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-20 12:00 UTC, ffleandro requested changes

2019-12-20 12:00 UTC, ffleandro commented on src/test/java/org/entando/plugins/pda/pam/service/task/KieTaskFormServiceTest.java
> +        kieTaskFormService.getTaskForm(connection, TASK_DEFINITION_ID);
Use `UUID.randomUUID().toString()` instead of `TASK_DEFINITION_ID`

2019-12-20 18:31 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-20 18:33 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-26 19:51 UTC, ffleandro submitted a review, later dismissed

2019-12-26 19:54 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-26 19:57 UTC, ffleandro approved these changes

2019-12-26 20:04 UTC, ffleandro commented
Retest this please

2019-12-26 20:04 UTC, entando-service commented
All is well

2019-12-26 20:05 UTC, merged