PDA-60 Redesign Task Model and refactored TaskService to use Kie Client Library
entando/pda-redhatpam-engine pull request #19
Opened 2020-01-04 00:11 UTC by ffleandro

2020-01-04 00:11 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-04 01:16 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-08 14:58 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-08 15:00 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-08 15:07 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-09 02:07 UTC, werbth requested changes

2020-01-09 02:07 UTC, werbth commented on src/main/java/org/entando/plugins/pda/pam/service/task/KieTaskCommentService.java
> +                    || e.getHttpCode().equals(HttpStatus.INTERNAL_SERVER_ERROR.value())*/) {
Remove commented code. I think the whole comment can be removed.

2020-01-09 13:32 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-09 13:41 UTC, werbth approved these changes

2020-01-09 13:41 UTC, werbth commented
Retest this please

2020-01-09 13:42 UTC, entando-service commented
All is well

2020-01-09 13:45 UTC, merged