PDA-17 Added endpoints to submit a new process form
entando/pda-redhatpam-engine pull request #24
Opened 2020-01-23 21:58 UTC by ffleandro

Added endpoints to submit a new process form
Added support to SubForm field types;
Improved Task form tests with data from MortageProcess example;

2020-01-23 21:58 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-30 09:10 UTC, werbth requested changes

2020-01-30 09:10 UTC, werbth commented on src/main/java/org/entando/plugins/pda/pam/service/process/KieFormDeserializer.java
> +                                .required(getBoolean(field, "required"))
`getBoolean` can return null and its value is assigned to `required` and `readOnly` attributes, which are primitive booleans. This can cause NPE. To do the unboxing correctly, getBoolean should return TRUE or FALSE.

2020-01-30 09:10 UTC, werbth commented on src/main/java/org/entando/plugins/pda/pam/service/process/KieFormDeserializer.java
> +                log.error(String.format("Invalid field Type: %s", field.get("code").asText()), e);
No need for `String.format` since log methods already support formatting: `log.error("Invalid field Type: {}", field.get("code").asText(), e);`

2020-01-30 09:10 UTC, werbth commented on src/main/java/org/entando/plugins/pda/pam/service/task/KieTaskFormService.java
> +            return id;
Because of this change, `taskService` attribute is not required anymore and can be removed from this class.

2020-01-30 19:08 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-30 19:23 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-30 19:39 UTC, werbth commented
Retest this please

2020-01-30 19:39 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-30 21:05 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-30 21:08 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-30 23:00 UTC, werbth commented
Retest this please

2020-01-30 23:00 UTC, entando-service commented
Something went wrong. Investigate!

2020-01-31 13:58 UTC, werbth commented
Retest this please

2020-01-31 14:00 UTC, entando-service commented
All is well

2020-01-31 14:04 UTC, werbth approved these changes

2020-01-31 14:04 UTC, merged